spring:
  application:
    name: salon-scheduling-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/salon_scheduling
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  servlet:
    context-path: /api
